=begin
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

                        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
=end

class Problem44
  pentagonal = []
  for n in 1000...2400
    pentagonal << (n*(3*n - 1)) / 2
  end

  pairs = pentagonal.repeated_combination(2).to_a
  for i in 0..pairs.size-1
    if pentagonal.include?(pairs[i][0] + pairs[i][1]) and pentagonal.include?(pairs[i][1] - pairs[i][0])
      p pairs[i][1] - pairs[i][0]
    end
  end
end