=begin
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
=end

class Problem45
  #triangle = []
  pentagonal = []
  hexagonal = []
  for n in 10_000..100_000
    #triangle << (n * (n + 1)) / 2
    pentagonal << (n * (3*n - 1)) / 2
    hexagonal << n * (2*n - 1)
  end

  for i in 0..hexagonal.size-1
    p hexagonal[i] if pentagonal.include?(hexagonal[i])
  end
end